// src/app/industries/healthcare-ai-solutions/annnimate-starter-pack/annnimate-starter-pack/text-reveal/text-reveal.jsx
'use client';

import { useRef, useState, useEffect } from 'react';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { SplitText } from 'gsap/SplitText';
import './text-reveal.css';

if (typeof window !== 'undefined') {
  gsap.registerPlugin(useGSAP, ScrollTrigger, SplitText);
}

/**
 * TextReveal Component
 * Professional text reveal animation using GSAP SplitText with line masking. Text slides up from
 * behind masks as you scroll, creating a clean, editorial reveal effect.
 *
 * @param {string} [className=''] - Additional CSS classes
 * @param {React.ReactNode} children - Text content to animate
 * @param {string} [type='words'] - Split type ('lines', 'words', 'chars')
 * @param {string} [start='top 80%'] - ScrollTrigger start position
 * @param {string} [end=''] - ScrollTrigger end position (for scrub)
 * @param {boolean|number} [scrub=false] - Link animation to scroll (false, true, or smoothness number)
 * @param {number} [duration=0.8] - Animation duration (seconds)
 * @param {number} [stagger=0.08] - Stagger delay between elements
 * @param {string} [ease='expo.out'] - GSAP easing function
 * @param {number} [yPercent=110] - Initial Y offset percentage
 * @param {boolean} [markers=false] - Show ScrollTrigger debug markers
 * @param {function} [onComplete] - Callback when animation completes
 */
export default function TextReveal({
  className = '',
  children,
  type = 'words',
  start = 'top 80%',
  end = '',
  scrub = false,
  duration = 0.8,
  stagger = 0.08,
  ease = 'expo.out',
  yPercent = 110,
  markers = false,
  onComplete,
}) {
  const containerRef = useRef(null);
  const textRef = useRef(null);
  const splitRef = useRef(null);
  const [fontsLoaded, setFontsLoaded] = useState(false);

  // Wait for fonts before SplitText
  useEffect(() => {
    if (typeof window !== 'undefined') {
      document.fonts.ready.then(() => setFontsLoaded(true));
    }
  }, []);

  useGSAP(
    () => {
      if (!fontsLoaded || !textRef.current) return;
      if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

      // Determine split types
      const typesToSplit =
        type === 'lines'
          ? 'lines'
          : type === 'words'
            ? 'lines,words'
            : 'lines,words,chars';

      // Split text with masking
      splitRef.current = new SplitText(textRef.current, {
        type: typesToSplit,
        linesClass: 'split-line',
        wordsClass: 'split-word',
        charsClass: 'split-char',
      });

      // Get animation targets based on type
      const targets = splitRef.current[type];

      // CRITICAL: Set initial position BEFORE making visible to prevent FOUC
      gsap.set(targets, {
        yPercent,
        force3D: true,
        willChange: 'transform',
      });
      gsap.set(textRef.current, { autoAlpha: 1 });

      // Parse scrub value
      const scrubValue =
        scrub === 'true' || scrub === true
          ? true
          : typeof scrub === 'number' || !isNaN(parseFloat(scrub))
            ? parseFloat(scrub)
            : false;

      // Animate text reveal
      gsap.to(targets, {
        yPercent: 0,
        duration,
        stagger,
        ease,
        force3D: true,
        scrollTrigger: {
          trigger: containerRef.current,
          start,
          end: end || undefined,
          scrub: scrubValue,
          once: !scrubValue,
          markers,
        },
        onComplete: () => {
          // Clear willChange after animation
          gsap.set(targets, { willChange: 'auto' });
          onComplete?.();
        },
      });

      // Cleanup
      return () => {
        if (splitRef.current) {
          splitRef.current.revert();
        }
        ScrollTrigger.getAll().forEach((st) => st.kill());
        if (targets) {
          gsap.killTweensOf(targets);
        }
      };
    },
    {
      scope: containerRef,
      dependencies: [fontsLoaded, type, start, end, scrub, duration, stagger, ease, yPercent, markers],
    }
  );

  return (
    <div ref={containerRef} className={`text_reveal_wrap ${className}`.trim()}>
      <div
        ref={textRef} data-anm-scroll-text-reveal className="text_reveal_text"
        style={{ visibility: 'hidden' }}
      >
        {children}
      </div>
    </div>
  );
}

// src/app/services/ai-development-services/annnimate-starter-pack/annnimate-starter-pack/text-reveal/text-reveal.vue
<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { SplitText } from 'gsap/SplitText'

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger, SplitText)
}

const props = defineProps({
  // type: Split type for reveal animation (lines | words | chars)
  type: {
    type: String,
    default: 'words'
  },
  // start: ScrollTrigger start position
  start: {
    type: String,
    default: 'top 80%'
  },
  // end: ScrollTrigger end position (for scrubbed animations)
  end: {
    type: String,
    default: ''
  },
  // scrub: Link animation to scroll position (false | true | smoothness number)
  scrub: {
    type: [Boolean, Number, String],
    default: false
  },
  // duration: Animation duration in seconds (0.3-2)
  duration: {
    type: Number,
    default: 0.8
  },
  // ease: GSAP easing function
  ease: {
    type: String,
    default: 'power4.out'
  },
  // stagger: Stagger delay between words/characters (0.01-0.2s)
  stagger: {
    type: Number,
    default: 0.05
  },
  // delay: Delay before animation starts (0-2s)
  delay: {
    type: Number,
    default: 0
  },
  // opacity: Starting opacity value (0-1)
  opacity: {
    type: Number,
    default: 0
  },
  // yPercent: Starting Y position as percentage (-100 to 100)
  yPercent: {
    type: Number,
    default: 100
  },
  // markers: Show ScrollTrigger debug markers
  markers: {
    type: Boolean,
    default: false
  }
})

const containerRef = ref(null)
const textRef = ref(null)

let ctx
let splitInstance = null

function parseScrub(value) {
  if (value === true || value === 'true') return true
  if (value === false || value === 'false') return false
  const num = parseFloat(value)
  return isNaN(num) ? false : num
}

function buildAnimation() {
  if (ctx) ctx.revert()
  if (splitInstance) {
    splitInstance.revert()
    splitInstance = null
  }

  if (!containerRef.value || !textRef.value) return
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return

  const typesToSplit =
    props.type === 'lines'
      ? 'lines'
      : props.type === 'words'
        ? 'lines,words'
        : 'lines,words,chars'

  const scrubValue = parseScrub(props.scrub)

  ctx = gsap.context(() => {
    splitInstance = SplitText.create(textRef.value, {
      type: typesToSplit,
      mask: 'lines',
      autoSplit: true,
      linesClass: 'split-line',
      wordsClass: 'split-word',
      charsClass: 'split-char',
      onSplit(instance) {
        const targets = instance[props.type]

        gsap.set(targets, {
          yPercent: props.yPercent,
          opacity: props.opacity,
          force3D: true,
          willChange: 'transform'
        })

        gsap.set(textRef.value, { autoAlpha: 1 })

        return gsap.to(targets, {
          yPercent: 0,
          opacity: 1,
          duration: props.duration,
          stagger: props.stagger,
          ease: props.ease,
          delay: props.delay,
          force3D: true,
          scrollTrigger: {
            trigger: containerRef.value,
            start: props.start,
            end: props.end || undefined,
            scrub: scrubValue,
            once: !scrubValue,
            invalidateOnRefresh: true,
            markers: props.markers
          },
          onComplete() {
            gsap.set(targets, { willChange: 'auto' })
          }
        })
      }
    })
  }, containerRef.value)
}

onMounted(async () => {
  await document.fonts.ready
  buildAnimation()
})

onUnmounted(() => {
  if (splitInstance) {
    splitInstance.revert()
    splitInstance = null
  }
  ctx?.revert()
})

watch(
  () => [props.type, props.start, props.end, props.scrub, props.duration, props.ease, props.stagger, props.delay, props.opacity, props.yPercent, props.markers],
  async () => {
    await document.fonts.ready
    buildAnimation()
  }
)
</script>

<template>
  <div ref="containerRef" class="text_reveal_wrap">
    <div
      ref="textRef"
      class="text_reveal_text"
      data-anm-scroll-text-reveal
      style="visibility: hidden"
    >
      <slot />
    </div>
  </div>
</template>
